Test after migration to Weasel. Cleaning bailout procedure upon quiting

diff --git a/robot/go b/robot/go
--- a/robot/go
+++ b/robot/go
@@ -14,24 +14,13 @@
 
 PATH=/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/sbin:/usr/sbin
 
-CROB_HOME=.
-
-CROB=$CROB_HOME
-cd $CROB
-
-if ! $CROB/checkexist.sh; then
-	exit 1
+if lsmod | grep -E -q 'pwrdaq'; then
+    echo "PowerDAQ module already loaded."
+else
+    echo "Loading PowerDAQ module."
+    ./loadmodules.sh
 fi
 
-# TODO: do we really want to keep loading/unloading the modules?
-# if our modules are already loaded, unload them first.
-
-lsmod | grep -E -q 'xeno_|pwrdaq|pci4e' && {
-	echo "some modules already loaded, reloading."
-	./stop || { 
-		echo "couldn't unload, exiting."; exit 1
-	}
-}
 
 if pkill -0 -x robot; then
     echo "old robot still running, stopping."
@@ -40,19 +29,10 @@ if pkill -0 -x robot; then
     }
 fi
 
+
+
 # flush disk buffers, could help in case something crashes.
 sync;sync
-
-# TODO: delete # echo inserting RTLinux modules...
-# TODO: delete insmod /usr/src/linux-2.4.18-rtl3.1/rtlinux-3.1/drivers/mbuff/mbuff.o
-# TODO: delete # echo inserting RTLinux modules...
-# TODO: delete (cd /usr/src/linux/rtlinux; scripts/insrtl)
-# TODO: delete ## echo inserting UEI powerDAQ module...
-# TODO: delete #insmod /lib/modules/2.4.18-w4l-rtl3.1/misc/pwrdaq.o
-# TODO: delete ## echo inserting IMT robot module...
-# TODO: delete #insmod ./robot.o
-
-./loadmodules.sh
 
 # /proc/pwrdaq has been loaded, and should be present.
 
@@ -67,19 +47,21 @@ while [ ! -r /proc/pwrdaq ]; do
     sleep 0.1
 done
 
-./robot &
-
-I=0
-while ! pkill -0 -x robot ; do
-    if [ $I -gt 20 ]; then
-	echo "go: could not start robot"
-	./stop
-	exit 1
-    fi
-    I=`expr $I + 1`
-    sleep 0.1
-done
+sudo ./robot &
 
 sleep 0.1
+
+#I=0
+#while ! pkill -0 -x robot ; do
+#    if [ $I -gt 20 ]; then#
+#	echo "go: could not start robot"
+#	./stop
+#	exit 1
+#    fi
+#    I=`expr $I + 1`
+#    sleep 0.1
+#done
+
+#sleep 0.1
 
 exit 0
diff --git a/robot/stop b/robot/stop
--- a/robot/stop
+++ b/robot/stop
@@ -13,10 +13,6 @@
 
 PATH=/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/sbin:/usr/sbin
 
-# this can be handy:
-export CROB_HOME=`pwd`
-CROB=$CROB_HOME
-#cd $CROB
 
 # are there user mode procs to kill?
 # these should be killed by the progs that create them
@@ -52,9 +48,9 @@ done
 # pkill (with the default SIGTERM) should work as well as sending quit above.
 
 if pkill -0 -x robot; then
-      pkill -x robot
-      echo "stop: sent pkill to robot process."
-      sleep 2
+    sudo pkill -x robot
+    echo "stop: sent pkill to robot process."
+    sleep 2
 fi
 
 # last resort, try SIGKILL.
@@ -75,27 +71,23 @@ fi
 
 # are there modules to unload?
 
-lsmod | grep -E -q 'xeno_|pwrdaq|pci4e' || {
-	echo "stop: no robot modules to unload."
+lsmod | grep -E -q 'pwrdaq' || {
+	echo "stop: no PowerDAQ modules to unload."
 	# lsmod
 	exit 0
 }
 
 # echo stopping modules...
-# TODO: delete rmmod robot
-# TODO: delete rmmod pwrdaq
-# TODO: delete (cd /usr/src/linux/rtlinux; scripts/rmrtl)
-# TODO: delete rmmod mbuff
 ./unloadmodules.sh
 
 I=0
 while true ; do 
-    lsmod | grep -E -q 'xeno_|pwrdaq|pci4e'
+    lsmod | grep -E -q 'pwrdaq'
     if [ $? ] ; then 
 	break
     fi
     if [ $I -gt 20 ]; then
-	echo "stop: could not unload kernel modules."
+	echo "stop: could not unload PowerDAQ kernel module."
 	exit 1
     fi
     I=`expr $I + 1`
